language: rust
dist: trusty
sudo: required
rust:
- beta
- nightly
- stable

os:
  - linux
#  - osx

before_script:
- |
  sudo pip install travis-cargo

script:
- |
  travis-cargo build -- --all-features &&
  travis-cargo test -- --all-features &&
  travis-cargo --only stable doc -- --all-features

env:
  global:
  - RUST_TEST_THREADS=1
  - LD_LIBRARY_PATH: "/usr/local/lib"