language: rust
dist: trusty
sudo: required
rust:
- beta
- nightly
- stable

cache:
  directories:
  - target

os:
  - linux

matrix:
  include:
  - os: osx
    rust: stable
  - rust: stable
    install:
      - rustup component add rustfmt-preview
    before_script:
      - cargo fmt --all -- --write-mode diff

script:
- cargo build
- cargo test --all

env:
  global:
  - RUST_TEST_THREADS=1
  - LD_LIBRARY_PATH: "/usr/local/lib"
