dist: trusty
sudo: required
language: rust

os:
  - linux

rust:
  - stable
  - beta
  - nightly

matrix:
  include:
  - os: osx
    osx_image: xcode11.3
    rust: stable

env:
  global:
  - RUST_BACKTRACE=1

cache: false

install:
  - if [ "${TRAVIS_OS_NAME}" == osx ]; then
      brew install openssl;
    fi

before_script:
  - rustup default nightly-2019-09-05
  - rustup component add rustfmt-preview
  - rustup component add clippy

script:
  - make clippy
  - cargo fmt --all -- --check
  - cargo build
  - cargo test --all
