dist: bionic
language: rust

os:
  - linux

rust:
  - nightly

cache:
  directories:
  - "$BUILD_DIR/aws"

addons:
  apt:
    sources:
      - llvm-toolchain-bionic-7
    packages:
      - clang-format-7

jobs:
  include:
  - os: linux
    rust: nightly
    env: FEATURES="encryption,jemalloc,portable,sse,cloud"
  - os: linux
    arch: arm64
    rust: nightly
  - os: osx
    osx_image: xcode11.5
    rust: nightly
  - env: TASK="clang-format"

env:
  global:
  - RUST_BACKTRACE=1

cache: false

before_script:
  # Increase the maximum number of open file descriptors, since some tests use
  # more FDs than the default limit.
  - ulimit -n 8192
  # Install AWS-SDK.
  - pushd /tmp && wget https://github.com/aws/aws-sdk-cpp/archive/1.8.14.tar.gz -O /tmp/aws-sdk.tar.gz && tar -xvf /tmp/aws-sdk.tar.gz > /dev/null && popd
  - pushd /tmp/aws-sdk-cpp-1.8.14 && cmake -DBUILD_ONLY='kinesis;core;s3;transfer' -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_TESTING=OFF . && make -j4 all && sudo make install && popd
  - rustup component add rustfmt-preview
  - rustup component add clippy

script:
  # copile rocksdb may cost more than 10 minutes, see https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
  - if [ "${TASK}" == "clang-format" ]; then
      bash ./travis-build/travis-format.sh;
    else
      travis_wait make clippy;
      cargo fmt --all -- --check;
      cargo build --features=$FEATURES;
      cargo test --all --features=$FEATURES;
    fi
