language: rust
dist: trusty
sudo: required
rust:
- beta
- nightly
- stable

os:
  - linux
#  - osx

before_script:
- |
  sudo pip install travis-cargo

script:
- |
  cargo build --features static-link
  cargo test --all --features static-link

env:
  global:
  - RUST_TEST_THREADS=1
  - LD_LIBRARY_PATH: "/usr/local/lib"