language: rust
dist: trusty
sudo: required
rust:
- beta
- nightly
- stable

cache:
  directories:
  - target

os:
  - linux

matrix:
  include:
    - os: osx
      rust: stable

script:
- cargo build
- cargo test --all -- --nocapture

env:
  global:
  - RUST_TEST_THREADS=1
  - LD_LIBRARY_PATH: "/usr/local/lib"
