language: rust
dist: trusty
sudo: required

cache:
  directories:
  - target


matrix:
  include:
    - os: linux
      rust: nightly
      env: SKIP_FORMAT_CHECK=false
    - os: linux
      rust: beta
      env: SKIP_FORMAT_CHECK=true
    - os: linux
      rust: stable
      env: SKIP_FORMAT_CHECK=true

before_script:
- 'if [ ${SKIP_FORMAT_CHECK} != "true" ]; then
      make -f travis-build/Makefile prepare-rustfmt;
  fi'

script:
- 'if [ ${SKIP_FORMAT_CHECK} != "true" ]; then
      cargo fmt -- --write-mode diff || (echo please make format and run tests before creating a pr!; exit 1);
  fi'
- cargo build --features static-link
- cargo test --all --features static-link

env:
  global:
  - RUST_TEST_THREADS=1
  - LD_LIBRARY_PATH: "/usr/local/lib"
