[package]

name = "rocksdb"
description = "A Rust wrapper for Facebook's RocksDB embeddable database."
version = "0.3.0"
authors = ["Tyler Neely <t@jujit.su>", "David Greenberg <dsg123456789@gmail.com>"]
license = "Apache-2.0"
keywords = ["database", "embedded", "LSM-tree", "persistence"]
homepage = "https://github.com/spacejam/rust-rocksdb"
exclude = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "tests/**/*",
]

[features]
default = []
valgrind = []
static-link = ["librocksdb_sys/static-link"]
portable = ["librocksdb_sys/portable"]

[[test]]

name = "test"
path = "tests/test.rs"

[dependencies]
libc = "0.2.11"
tempdir = "0.3.4"

[dependencies.librocksdb_sys]
path = "librocksdb_sys"
