[package]
name = "librocksdb_sys"
version = "0.1.0"
authors = ["Jay Lee <busyjaylee@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2.11"
tempdir = "0.3"

[features]
default = []
static-link = []
# portable doesn't require static link, though it's meaningless
# when not using with static-link right now in this crate.
portable = []
sse = []

[build-dependencies]
gcc = "0.3"
pkg-config = "0.3.8"
